# Generated by Django 4.0.6 on 2024-05-30 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0002_direcor'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Direcor',
            new_name='Director',
        ),
    ]
