# Generated by Django 5.0.6 on 2024-07-16 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cartelera', '0012_cine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pelicula',
            name='portada',
        ),
    ]
